services:
  postgres:
    image: postgres:16-alpine
    container_name: football-squares-postgres
    environment:
      POSTGRES_DB: football_squares
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - football_squares_postgres:/var/lib/postgresql/data

volumes:
  football_squares_postgres:
